[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[browser]
serverAddress = "localhost"
serverPort = 8501

[server]
maxUploadSize = 500
enableCORS = false
enableXsrfProtection = true

[client]
showErrorDetails = true
